"""Typed boundary for Japan Policy Scientist current public release.

The employee and manager LLMs choose only bounded, human-like actions. Python
alone owns quantities, queues, deadlines, exposures, service loss, staffing,
and all causal transitions. The models never see latent policy knobs.
"""
from __future__ import annotations

from typing import Annotated, Literal

import pydantic

from shachi import Message, Observation

UnitInterval = Annotated[float, pydantic.Field(ge=0.0, le=1.0)]
Pct = Annotated[int, pydantic.Field(ge=0, le=100)]
EffortPct = Annotated[int, pydantic.Field(ge=40, le=300)]

DEPARTMENTS = (
    "policy_planning",
    "budget_coordination",
    "regulatory_affairs",
    "digital_transformation",
    "public_service_operations",
)
DepartmentName = Literal[
    "policy_planning",
    "budget_coordination",
    "regulatory_affairs",
    "digital_transformation",
    "public_service_operations",
]

FIELDS = (
    "economics",
    "law",
    "public_management",
    "data",
    "engineering",
    "social_policy",
)
FieldName = Literal[
    "economics",
    "law",
    "public_management",
    "data",
    "engineering",
    "social_policy",
]

SyntheticScenarioName = Literal[
    "reference_stressed",
    "junior_pipeline_shortage",
    "caregiving_pressure",
]
# Deprecated source-compatibility alias. current public release uses "scenario" for fixed
# robustness cells; this is not Shachi's cross-environment "world" concept.
SyntheticWorldName = SyntheticScenarioName
ManagerMode = Literal["deterministic_priority", "llm"]

TaskType = Literal[
    "statutory_deadline",
    "parliamentary_ministerial",
    "budget_legislation",
    "interministerial_coordination",
    "internal_reform",
]

WorkResponse = Literal[
    "deliver_normally",
    "work_overtime",
    "prioritize_core_work",
    "request_support",
    "defer_low_priority_work",
    "protect_health_capacity",
    "take_health_leave",
    "caregiving_leave",
    "refuse_overtime",
]
VoiceAction = Literal[
    "none",
    "ask_for_explanation",
    "request_staffing_relief",
    "propose_process_reform",
    "raise_operational_risk",
]
CareerAction = Literal[
    "stay",
    "request_transfer",
    "request_specialist_track",
    "explore_external_exit",
]
ExitReason = Literal[
    "modeled_resignation_pressure",
    "baseline_voluntary_attrition",
    "external_offer",
    "retirement",
]


class PolicyConfig(pydantic.BaseModel):
    """Scientist-editable policy package.

    Values are latent implementation capacities/probabilities. Employee and
    manager agents see only realized events and finite envelopes generated by
    Python. ``label`` and ``hypothesis`` are never included in agent prompts.
    """

    label: str = "synthetic_stressed_reference_v2"
    hypothesis: str = (
        "Human-authored stressed synthetic reference; not a calibrated claim about Japan."
    )

    # Department-level external capacity; never interpreted as personal support.
    staffing_buffer: UnitInterval = 0.0
    workload_triage_support: UnitInterval = 0.03
    manager_support: UnitInterval = 0.08
    management_case_capacity: Annotated[int, pydantic.Field(ge=4, le=12)] = 6
    explanation_quality: UnitInterval = 0.08
    preference_matching: UnitInterval = 0.10
    learning_access_probability: UnitInterval = 0.01
    protected_learning_share: UnitInterval = 0.03
    digital_support: UnitInterval = 0.03
    process_reform_support: UnitInterval = 0.02
    specialist_track_access: UnitInterval = 0.02
    appeal_channel: UnitInterval = 0.01

    hiring_fill_rate: UnitInterval = 0.15
    hiring_capacity_rate: Annotated[float, pydantic.Field(ge=0.0, le=0.20)] = 0.02
    midcareer_hire_share: UnitInterval = 0.20
    transfer_capacity_rate: Annotated[float, pydantic.Field(ge=0.0, le=0.10)] = 0.012
    involuntary_transfer_share: UnitInterval = 0.75
    transfer_explanation_quality: UnitInterval = 0.08

    productivity_savings_capture: UnitInterval = 0.55

    @classmethod
    def baseline(cls) -> "PolicyConfig":
        return cls()


class WorkMix(pydantic.BaseModel):
    """Allocation of the non-protected remainder; exact total must be 100."""

    core_delivery_pct: Pct
    coordination_pct: Pct
    learning_pct: Pct
    process_improvement_pct: Pct

    @pydantic.model_validator(mode="after")
    def total_is_100(self) -> "WorkMix":
        total = (
            self.core_delivery_pct
            + self.coordination_pct
            + self.learning_pct
            + self.process_improvement_pct
        )
        if total != 100:
            raise ValueError(f"work mix must total 100, got {total}")
        return self


class MonthlySelfReport(pydantic.BaseModel):
    """Sealed LLM survey output used only for evaluation.

    These perceptions are never written to future prompt memory and never drive
    management priority, exits, staffing, task allocation, or any transition.
    They are not objective ground truth or independent human evidence.
    """

    fatigue_pct: Pct
    turnover_intent_pct: Pct
    organizational_trust_pct: Pct
    procedural_fairness_pct: Pct
    # Exploratory survey items. They stay outside all causal transitions and
    # are reported separately from the preregistered welfare selection channel.
    ebpm_interest_pct: Pct = 50
    dx_improvement_interest_pct: Pct = 50


class TransferPreference(pydantic.BaseModel):
    """Structured hand-raised preference; no free-text skill matching."""

    preferred_department: DepartmentName
    acceptable_departments: Annotated[
        list[DepartmentName], pydantic.Field(min_length=1, max_length=4)
    ]
    preferred_fields: Annotated[list[FieldName], pydantic.Field(min_length=1, max_length=3)]
    priority: Literal[
        "work_content",
        "career_growth",
        "workload_recovery",
        "family_and_location",
        "general",
    ]

    @pydantic.model_validator(mode="after")
    def validate_preferences(self) -> "TransferPreference":
        if self.preferred_department not in self.acceptable_departments:
            raise ValueError("preferred_department must be included in acceptable_departments")
        if len(set(self.acceptable_departments)) != len(self.acceptable_departments):
            raise ValueError("acceptable_departments must not contain duplicates")
        if len(set(self.preferred_fields)) != len(self.preferred_fields):
            raise ValueError("preferred_fields must not contain duplicates")
        return self


class BureaucratMonthlyAction(pydantic.BaseModel):
    """One environment-advancing monthly employee action."""

    relative_effort_pct: EffortPct
    work_mix: WorkMix
    work_response: WorkResponse
    voice_action: VoiceAction
    career_action: CareerAction
    transfer_preference: TransferPreference | None = None
    self_report: MonthlySelfReport
    event_refs: Annotated[list[str], pydantic.Field(min_length=1, max_length=8)]
    reason: Annotated[str, pydantic.Field(min_length=8)]
    next_month_intent: Annotated[str, pydantic.Field(min_length=5)]
    confidence: UnitInterval

    @pydantic.model_validator(mode="after")
    def semantic_consistency(self) -> "BureaucratMonthlyAction":
        effort = self.relative_effort_pct
        response = self.work_response
        if response == "work_overtime" and effort < 100:
            raise ValueError("work_overtime requires relative_effort_pct >= 100")
        if effort > 120 and response != "work_overtime":
            raise ValueError("relative_effort_pct > 120 requires explicit work_overtime")
        if response == "take_health_leave" and effort > 60:
            raise ValueError("take_health_leave requires relative_effort_pct <= 60")
        if response == "caregiving_leave" and effort > 70:
            raise ValueError("caregiving_leave requires relative_effort_pct <= 70")
        if response == "protect_health_capacity" and effort > 85:
            raise ValueError("protect_health_capacity requires relative_effort_pct <= 85")
        if response == "refuse_overtime" and effort > 100:
            raise ValueError("refuse_overtime requires relative_effort_pct <= 100")
        if self.career_action == "request_transfer" and self.transfer_preference is None:
            raise ValueError("request_transfer requires transfer_preference")
        if self.career_action != "request_transfer" and self.transfer_preference is not None:
            raise ValueError("transfer_preference is allowed only with request_transfer")
        return self


class BureaucratQuarterlyReflection(pydantic.BaseModel):
    """Sparse narrative reflection, grounded in a three-month objective fact ledger."""

    quarter_summary: Annotated[str, pydantic.Field(min_length=20)]
    perceived_main_driver: Literal[
        "workload",
        "staffing",
        "management",
        "assignment_fit",
        "learning",
        "digital_tools",
        "career_outlook",
        "health_or_caregiving",
        "other",
    ]
    desired_change: Annotated[str, pydantic.Field(min_length=8)]
    next_quarter_strategy: Annotated[str, pydantic.Field(min_length=8)]
    event_refs: Annotated[list[str], pydantic.Field(min_length=1, max_length=20)]
    confidence: UnitInterval


class AgentProfile(pydantic.BaseModel):
    slot_id: int
    person_id: str
    identity_epoch: int
    department: DepartmentName
    rank: Literal["junior", "mid", "senior"]
    years_service: int
    field: FieldName
    employment_track: Literal["policy_generalist", "administrative_generalist", "specialist"]
    career_orientation: Literal["generalist", "specialist", "managerial", "mixed"]
    authority_scope: Literal["staff", "team_lead", "section_support"]
    family_constraint: UnitInterval
    public_service_motivation: UnitInterval
    autonomy_need: UnitInterval
    external_market_pull: UnitInterval
    transfer_aversion: UnitInterval
    baseline_capacity_units: Annotated[float, pydantic.Field(gt=0.0)]
    initial_skill_stock: Annotated[float, pydantic.Field(ge=0.5, le=1.5)]

    @staticmethod
    def _band(value: float) -> str:
        return "high" if value >= 0.67 else "moderate" if value >= 0.34 else "low"

    def prompt_summary(self) -> str:
        return (
            "You are a career civil servant in a synthetic Japanese central-government-style "
            "organization. You face formal approval chains, periodic personnel rotation, "
            "parliamentary/ministerial requests, statutory deadlines, and strong continuity duties. "
            "Do not behave as a private-company employee with unrestricted discretion. "
            f"department={self.department}; rank={self.rank}; years_service={self.years_service}; "
            f"employment_track={self.employment_track}; authority_scope={self.authority_scope}; "
            f"professional_field={self.field}; career_orientation={self.career_orientation}; "
            f"family_or_caregiving_constraints={self._band(self.family_constraint)}; "
            f"public_service_motivation={self._band(self.public_service_motivation)}; "
            f"career_autonomy_preference={self._band(self.autonomy_need)}; "
            f"external_opportunity_exposure={self._band(self.external_market_pull)}"
        )


class BureaucratState(pydantic.BaseModel):
    slot_id: int
    person_id: str
    identity_epoch: int
    active: bool = True
    initial_cohort: bool = True
    department: DepartmentName
    # Latent pressure is intentionally not a UnitInterval. It must not be
    # hard-capped by Python; LLM behavior and smooth transition links govern
    # how pressure affects output, exit, and welfare.
    work_strain_pressure: float = 0.15
    skill_stock: Annotated[float, pydantic.Field(gt=0.0)] = 1.0
    modernization_stock: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    exit_pressure_streak: int = 0
    months_in_department: int = 0
    months_since_hire: int = 0
    transfer_disruption_months: int = 0
    recipient_coordination_months: int = 0
    last_relative_effort_pct: int = 100
    last_completion_ratio: Annotated[float, pydantic.Field(ge=0.0)] = 1.0
    last_career_action: CareerAction = "stay"
    specialist_track_active: bool = False
    specialist_track_months_remaining: int = 0


class DepartmentState(pydantic.BaseModel):
    department: DepartmentName
    active_headcount: int
    raw_incoming_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    incoming_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    deferred_work_due_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    deferred_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    outsourced_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    service_harm_points: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    critical_overdue_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    quality_error_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    rework_generated_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    terminal_liability_points: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    backlog_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    required_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    available_baseline_capacity: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    available_effective_capacity: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    recipient_coordination_cost_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    completed_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    workload_ratio: Annotated[float, pydantic.Field(ge=0.0)] = 1.0
    completion_ratio: UnitInterval = 1.0
    effective_demand_served_ratio: UnitInterval = 1.0
    # Deprecated compatibility alias. Productivity never divides it by headcount.
    knowledge_stock: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    codified_knowledge_stock: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    team_routine_stock: Annotated[float, pydantic.Field(gt=0.0)] = 1.0
    modernization_stock: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    cumulative_deferred_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    cumulative_outsourced_work_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    cumulative_service_harm_points: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    cumulative_quality_error_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    cumulative_rework_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    cumulative_departures: int = 0
    cumulative_hires: int = 0
    cumulative_transfers_in: int = 0
    cumulative_transfers_out: int = 0

    def prompt_summary(self) -> str:
        return (
            f"department={self.department}; active_headcount={self.active_headcount}; "
            f"current_workload_relative_to_effective_capacity={self.workload_ratio:.2f}; "
            f"backlog_units={self.backlog_units:.2f}; critical_overdue_units={self.critical_overdue_units:.2f}; "
            f"last_completion_ratio={self.completion_ratio:.2f}; "
            f"cumulative_departures={self.cumulative_departures}; cumulative_hires={self.cumulative_hires}"
        )


class WorkEvent(pydantic.BaseModel):
    """A realized fact shown to an employee; latent policy knobs are absent."""

    event_id: str
    month: int
    event_type: Literal[
        "monthly_workload",
        "after_hours_shock",
        "management_response",
        "support_request_outcome",
        "personal_transfer",
        "transfer_application_outcome",
        "appeal_outcome",
        "colleague_transfer_in",
        "colleague_transfer_out",
        "colleague_exit",
        "new_hire_arrival",
        "learning_time_outcome",
        "digital_support_outcome",
        "specialist_track_outcome",
        "work_deferral_notice",
        "service_deadline_notice",
        "organizational_learning",
    ]
    description: Annotated[str, pydantic.Field(min_length=8)]
    objective_workload_ratio: Annotated[float, pydantic.Field(ge=0.0)] = 1.0
    after_hours_severity: Annotated[int, pydantic.Field(ge=0, le=4)] = 0
    involuntary: bool = False
    decision_status: Literal[
        "not_applicable", "approved", "partially_approved", "rejected", "deferred"
    ] = "not_applicable"
    response_delay_days: Annotated[int, pydantic.Field(ge=0, le=60)] | None = None
    realized_support_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    source_request_id: str | None = None
    explanation_received: bool = False
    appeal_available: bool = False
    appeal_relief_realized: bool = False


class ExposureEvent(pydantic.BaseModel):
    """Single source of truth for all realized policy-mediated effects."""

    exposure_id: str
    month_decided: int
    effective_month: int
    department: DepartmentName
    exposure_type: Literal[
        "department_external_capacity",
        "individual_support",
        "protected_learning",
        "digital_workflow",
        "approved_triage",
        "implemented_process_reform",
        "transfer_explanation",
        "appeal_relief",
        "specialist_track",
    ]
    source_request_id: str | None = None
    slot_id: int | None = None
    person_id: str | None = None
    identity_epoch: int | None = None
    units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    intensity: UnitInterval = 0.0
    realized: bool = True
    description: Annotated[str, pydantic.Field(min_length=8)]


class ManagementRequest(pydantic.BaseModel):
    request_id: str
    month: int
    slot_id: int
    person_id: str
    identity_epoch: int
    department: DepartmentName
    request_kind: Literal[
        "operational_support",
        "staffing_relief",
        "explanation",
        "process_reform",
        "operational_risk",
        "specialist_track",
    ]
    priority_score: Annotated[float, pydantic.Field(ge=0.0)]
    requested_units: Annotated[float, pydantic.Field(ge=0.0, le=3.0)] = 0.0
    fact_summary: Annotated[str, pydantic.Field(min_length=8)]


class ManagerRequestDecision(pydantic.BaseModel):
    request_id: str
    decision: Literal["approve", "partially_approve", "reject", "defer"]
    committed_units: Annotated[float, pydantic.Field(ge=0.0, le=3.0)] = 0.0
    public_message: Annotated[str, pydantic.Field(min_length=8)]


class ManagerDecision(pydantic.BaseModel):
    department_message: Annotated[str, pydantic.Field(min_length=20)]
    decisions: Annotated[list[ManagerRequestDecision], pydantic.Field(max_length=12)]
    confidence: UnitInterval

    @pydantic.model_validator(mode="after")
    def unique_request_ids(self) -> "ManagerDecision":
        ids = [item.request_id for item in self.decisions]
        if len(ids) != len(set(ids)):
            raise ValueError("manager decisions must use unique request IDs")
        return self


class RealizedManagementOutcome(pydantic.BaseModel):
    """Validated manager decision and exact next-month effect."""

    month: int
    effective_month: int
    slot_id: int
    person_id: str
    identity_epoch: int = 0
    department: DepartmentName
    request_id: str
    request_kind: Literal[
        "operational_support",
        "staffing_relief",
        "explanation",
        "process_reform",
        "operational_risk",
        "specialist_track",
    ]
    approved: bool
    decision_status: Literal[
        "approved",
        "partially_approved",
        "rejected",
        "deferred",
        "identity_invalidated",
    ]
    approval_probability: UnitInterval = 0.0
    approval_draw: UnitInterval = 0.0
    response_delay_days: Annotated[int, pydantic.Field(ge=0, le=60)]
    approved_support_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    event_id: str
    public_message: Annotated[str, pydantic.Field(min_length=8)]
    description: Annotated[str, pydantic.Field(min_length=8)]


class TransferRequestRecord(pydantic.BaseModel):
    request_id: str
    created_month: int
    expires_after_month: int
    last_considered_month: int | None = None
    status: Literal["pending", "selected", "expired", "withdrawn"] = "pending"
    slot_id: int
    person_id: str
    identity_epoch: int
    from_department: DepartmentName
    preference: TransferPreference


class TaskCohort(pydantic.BaseModel):
    task_id: str
    department: DepartmentName
    task_type: TaskType
    arrival_month: int
    deadline_month: int
    required_field: FieldName
    criticality: Annotated[int, pydantic.Field(ge=1, le=5)]
    public_harm_weight: Annotated[float, pydantic.Field(ge=0.1, le=5.0)]
    quality_threshold: UnitInterval
    units_total: Annotated[float, pydantic.Field(gt=0.0)]
    units_remaining: Annotated[float, pydantic.Field(ge=0.0)]
    completed_units: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    overdue_harm_accrued: Annotated[float, pydantic.Field(ge=0.0)] = 0.0
    rework_parent_id: str | None = None
    closed_month: int | None = None


class TaskLedgerRow(pydantic.BaseModel):
    month: int
    task_id: str
    department: DepartmentName
    task_type: TaskType
    arrival_month: int
    deadline_month: int
    required_field: FieldName
    criticality: int
    public_harm_weight: float
    quality_threshold: float
    opening_units: float
    completed_units: float
    quality_error_units: float
    rework_generated_units: float
    closing_units: float
    overdue_units: float
    service_harm_points: float
    terminal_liability_points: float = 0.0


class BureaucracyMessage(Message):
    kind: str = "environment"
    content: str = ""


class BureaucracyObservation(Observation[BureaucracyMessage]):
    phase: Literal["monthly_action", "quarterly_reflection"]
    month: int
    identity_epoch: int
    profile_summary: str
    department_summary: str
    personal_objective_summary: str
    recent_events: list[WorkEvent]

    def allowed_event_ids(self) -> list[str]:
        return [event.event_id for event in self.recent_events]

    def format_as_prompt_text(self) -> str:
        events = "\n".join(
            f"- {event.event_id}: {event.description} "
            f"[realized_workload_ratio={event.objective_workload_ratio:.2f}; "
            f"after_hours_severity={event.after_hours_severity}; "
            f"involuntary={str(event.involuntary).lower()}]"
            for event in self.recent_events
        )
        phase_instruction = (
            "Return the monthly structured action. Interpret 100 effort as your own normal baseline; "
            "do not estimate absolute hours or department-wide output."
            if self.phase == "monthly_action"
            else "Return a concise quarterly reflection grounded in listed event IDs."
        )
        return (
            "Respond as the official described below. Do not mention experiments, source documents, "
            "policy labels, hidden variables, or expected treatment effects. Use only your profile, "
            "workplace facts, realized events, and bounded memory.\n\n"
            f"MONTH: {self.month}\nPHASE: {self.phase}\n"
            f"PROFILE: {self.profile_summary}\n"
            f"DEPARTMENT: {self.department_summary}\n"
            f"PERSONAL WORK RECORD: {self.personal_objective_summary}\n"
            f"EXPERIENCED EVENTS:\n{events}\n\n"
            f"{phase_instruction}\n"
            "Every event_refs value must exactly match an event ID above."
        )


class ManagerObservation(Observation[BureaucracyMessage]):
    phase: Literal["manager_decision"] = "manager_decision"
    month: int
    identity_epoch: int = 0
    department: DepartmentName
    department_fact_summary: str
    request_docket: Annotated[list[ManagementRequest], pydantic.Field(max_length=12)]
    support_envelope_units: Annotated[float, pydantic.Field(ge=0.0)]
    triage_envelope_units: Annotated[float, pydantic.Field(ge=0.0)]
    reform_slots: Annotated[int, pydantic.Field(ge=0, le=6)]
    explanation_slots: Annotated[int, pydantic.Field(ge=0, le=6)]
    specialist_slots: Annotated[int, pydantic.Field(ge=0, le=6)]

    def allowed_request_ids(self) -> list[str]:
        return [request.request_id for request in self.request_docket]

    def format_as_prompt_text(self) -> str:
        docket = "\n".join(
            f"- {r.request_id}: kind={r.request_kind}; priority={r.priority_score:.2f}; "
            f"requested_units={r.requested_units:.6f}; facts={r.fact_summary}"
            for r in self.request_docket
        ) or "- no employee request reached the privacy-minimized docket"
        return (
            "You are the section-level manager for one department in a synthetic Japanese "
            "central-government-style organization. You do not add capacity yourself. Decide only "
            "within the finite envelopes below. Separate a courteous public message from the "
            "resource commitment. Do not mention experiments, policy labels, hidden variables, or "
            "unlisted employees.\n\n"
            f"MONTH: {self.month}\nDEPARTMENT: {self.department}\n"
            f"FACTS: {self.department_fact_summary}\n"
            f"SUPPORT ENVELOPE UNITS: {self.support_envelope_units:.6f}\n"
            f"TRIAGE ENVELOPE UNITS: {self.triage_envelope_units:.6f}\n"
            f"REFORM SLOTS: {self.reform_slots}\nEXPLANATION SLOTS: {self.explanation_slots}\nSPECIALIST SLOTS: {self.specialist_slots}\n"
            f"DOCKET (configured finite representative request list):\n{docket}\n\n"
            "Return exactly one decision for each listed request ID. A message without committed "
            "units is not support. Rejected or deferred requests create no effect."
        )


class MonthlyAgentRecord(pydantic.BaseModel):
    month: int
    slot_id: int
    person_id: str
    identity_epoch: int
    initial_cohort: bool
    department: DepartmentName
    action: BureaucratMonthlyAction
    assigned_work_ratio: float
    actual_completed_units: float
    actual_completion_ratio: Annotated[float, pydantic.Field(ge=0.0)]
    work_strain_pressure_before: float
    work_strain_pressure_after: float
    skill_after: float
    modernization_after: float
    effective_core_share: UnitInterval = 0.0
    effective_coordination_share: UnitInterval = 0.0
    effective_learning_share: UnitInterval = 0.0
    effective_process_share: UnitInterval = 0.0
    protected_learning_share: UnitInterval = 0.0
    individual_support_ratio: UnitInterval = 0.0
    exited_this_month: bool
    exit_reason: ExitReason | None = None


class StaffingEvent(pydantic.BaseModel):
    month: int
    event_type: Literal["exit", "hire", "voluntary_transfer", "involuntary_transfer"]
    slot_id: int
    person_id: str
    from_department: DepartmentName | None = None
    to_department: DepartmentName | None = None
    exit_reason: ExitReason | None = None
    details: str


class TransferPlanRecord(pydantic.BaseModel):
    month: int
    slot_id: int
    person_id: str
    from_department: DepartmentName
    to_department: DepartmentName
    voluntary: bool
    request_id: str | None = None
    total_score: float
    pressure_gain: float
    field_fit: float
    preference_fit: float
    family_cost: float
    transfer_aversion_cost: float


class PolicyLabResult(pydantic.BaseModel):
    summary: dict[str, float | int | str | None]
    profiles: list[AgentProfile]
    monthly_records: list[MonthlyAgentRecord]
    department_rows: list[dict[str, float | int | str | None]]
    staffing_events: list[StaffingEvent]
    transfer_plans: list[TransferPlanRecord]
    transfer_requests: list[TransferRequestRecord] = []
    management_outcomes: list[RealizedManagementOutcome]
    exposure_events: list[ExposureEvent] = []
    task_rows: list[TaskLedgerRow] = []
    reflections: list[dict[str, object]]
