"""Generate the final manuscript after immutable selection and frozen holdout."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from aider.coders import Coder
from aider.io import InputOutput
from aider.models import Model

from ai_scientist.llm import create_client
from ai_scientist.perform_writeup import (
    assert_no_placeholders,
    generate_latex,
    perform_writeup,
)
from ai_scientist.policy_context import get_aider_model_name

from claim_verifier import verify_claims
from paper_numeric_audit import audit as audit_paper_numbers
from selection_and_holdout import verify_selection_freeze
from verified_results import DEVELOPMENT_METRICS, generate as generate_verified_results


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp.{os.getpid()}")
    tmp.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    os.replace(tmp, path)


def _development_summary(run_root: Path) -> list[dict[str, Any]]:
    rows = []
    for index in range(5):
        run = run_root / f"run_{index}"
        manifest = _read_json(run / "run_manifest.json")
        means = _read_json(run / "final_info.json")["policy_lab"]["means"]
        rows.append(
            {
                "run": run.name,
                "label": manifest["intervention_policy"]["label"],
                "policy": manifest["intervention_policy"],
                "metrics": {key: means.get(key) for key in DEVELOPMENT_METRICS},
            }
        )
    return rows


def load_scientific_contexts(run_root: Path) -> dict[str, Any]:
    """Read the explicit model/context bundle given to the final-paper writer.

    The writer and Aider should not infer how Shachi works from release history or
    code archaeology.  These files are the stable research interface: model card,
    problem brief, policy-space contract, paper contract, and curated source cards.
    """
    contexts: dict[str, Any] = {"source_cards": {}}
    for name in (
        "scientist_model_card.md",
        "problem_context.md",
        "policy_space.json",
        "paper_contract.json",
    ):
        path = run_root / name
        if path.is_file():
            if path.suffix == ".json":
                contexts[name] = json.loads(path.read_text(encoding="utf-8"))
            else:
                contexts[name] = path.read_text(encoding="utf-8")
    cards_dir = run_root / "source_cards"
    if cards_dir.is_dir():
        for card in sorted(cards_dir.glob("*.md")):
            contexts["source_cards"][card.name] = card.read_text(encoding="utf-8")
    missing = [
        name
        for name in ("scientist_model_card.md", "problem_context.md", "policy_space.json")
        if name not in contexts
    ]
    if missing:
        raise FileNotFoundError(
            "Final paper context bundle is incomplete; missing " + ", ".join(missing)
        )
    return contexts


def _make_evidence(run_root: Path, idea: dict[str, Any]) -> tuple[Path, Path]:
    selection = _read_json(run_root / "selection_result.json")
    holdout_summary = (
        _read_json(run_root / "holdout_summary.json")
        if (run_root / "holdout_summary.json").is_file()
        else None
    )
    figures = sorted(
        str(path.relative_to(run_root))
        for path in (run_root / "figures").glob("*.png")
    ) if (run_root / "figures").is_dir() else []
    notes = (run_root / "notes.txt").read_text(encoding="utf-8") if (run_root / "notes.txt").is_file() else ""
    scientific_contexts = load_scientific_contexts(run_root)
    payload = {
        "schema_version": "1.1",
        "idea": idea,
        "selection": selection,
        "development": _development_summary(run_root),
        "holdout": holdout_summary,
        "figures": figures,
        "experiment_notes": notes,
        "scientific_contexts": scientific_contexts,
        "claim_boundary": (
            "All outcomes are generated by the declared synthetic organization model. "
            "They are not estimates of effects in real ministries or evidence about actual civil servants."
        ),
        "writing_rules": [
            "Use scientist_model_card.md and policy_space.json to describe Shachi, the environment, and policy interventions.",
            "Use verified_results.tex for numerical outcome values.",
            "Do not present employee rows or person-months as independent replications.",
            "Do not invent confidence intervals.",
            "Distinguish development selection from previously unused synthetic holdout cells.",
            "A negative selection result is a valid scientific result.",
            "Use the Wakate source card only as problem context, not as causal calibration or policy evidence.",
            "Do not include release-history, API-key, provider usage, file-hash, or implementation-debug language in the manuscript.",
        ],
    }
    json_path = run_root / "paper_evidence.json"
    md_path = run_root / "paper_evidence.md"
    _atomic_json(json_path, payload)
    lines = [
        "# Verified paper evidence",
        "",
        "This file is machine-generated after immutable selection and, when applicable, frozen holdout.",
        "It contains no API keys, provider usage data, or file-hash provenance.",
        "",
        "## Claim boundary",
        payload["claim_boundary"],
        "",
        "## How to understand the Shachi-based organization model",
        str(scientific_contexts.get("scientist_model_card.md", "")),
        "",
        "## Problem context and claim boundary",
        str(scientific_contexts.get("problem_context.md", "")),
        "",
        "## Machine-readable policy space",
        json.dumps(scientific_contexts.get("policy_space.json", {}), ensure_ascii=False, indent=2),
        "",
        "## Research program",
        json.dumps(idea, ensure_ascii=False, indent=2),
        "",
        "## Selection",
        json.dumps(selection, ensure_ascii=False, indent=2),
        "",
        "## Development results",
        json.dumps(payload["development"], ensure_ascii=False, indent=2),
        "",
        "## Frozen holdout",
        json.dumps(holdout_summary, ensure_ascii=False, indent=2),
        "",
        "## Curated local source cards",
        json.dumps(scientific_contexts.get("source_cards", {}), ensure_ascii=False, indent=2),
        "",
        "## Available figures",
        "\n".join(f"- {item}" for item in figures) or "- none",
        "",
        "## Writing rules",
        "\n".join(f"- {item}" for item in payload["writing_rules"]),
    ]
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return json_path, md_path

def _load_selected_idea(run_root: Path) -> dict[str, Any]:
    ideas = _read_json(run_root / "ideas.json")
    if not isinstance(ideas, list) or len(ideas) != 1:
        raise RuntimeError("Exactly one selected research idea is required")
    return ideas[0]


def _validate_final_prerequisites(run_root: Path) -> dict[str, Any]:
    selection = verify_selection_freeze(run_root)
    if selection.get("selected_policy") is not None:
        if not (run_root / "holdout_complete.json").is_file():
            raise FileNotFoundError("selected candidate requires holdout_complete.json before final paper")
        if not (run_root / "holdout_summary.json").is_file():
            raise FileNotFoundError("selected candidate requires holdout_summary.json before final paper")
    return selection


def _update_result_manifests(
    *, run_root: Path, stable_manifest: Path | None, final_manifest: dict[str, Any]
) -> None:
    paths = [run_root / "result_manifest.json"]
    if stable_manifest is not None:
        paths.append(stable_manifest)
    for path in paths:
        data = _read_json(path) if path.is_file() else {}
        data.update(
            {
                "status": "complete",
                "success": True,
                "phase": "final_paper_complete",
                "development_complete": True,
                "final_paper_path": final_manifest["final_paper_path"],
                "paper_path": final_manifest["final_paper_path"],
                "improved_paper_path": None,
                "claim_verification_path": final_manifest[
                    "claim_verification_path"
                ],
                "final_paper_manifest_path": str(
                    (run_root / "final_paper_manifest.json").resolve()
                ),
                "updated_at_utc": datetime.now(timezone.utc).replace(
                    microsecond=0
                ).isoformat(),
            }
        )
        _atomic_json(path, data)


def validate_existing_manifest(run_root: Path) -> dict[str, Any] | None:
    """Return a complete final-paper manifest only when every bound artifact matches."""
    manifest_path = run_root / "final_paper_manifest.json"
    if not manifest_path.is_file():
        return None
    payload = _read_json(manifest_path)
    if payload.get("status") != "complete" or payload.get("phase") != "post_selection_post_holdout_final_paper":
        raise RuntimeError("final_paper_manifest.json is not complete")
    bindings = {
        "final_paper_sha256": Path(str(payload.get("final_paper_path", ""))),
        "latex_sha256": run_root / "latex" / "template.tex",
        "verified_results_sha256": run_root / "verified_results.tex",
        "verified_claims_sha256": run_root / "verified_claims.json",
        "claim_verification_sha256": run_root / "claim_verification.json",
        "paper_evidence_json_sha256": run_root / "paper_evidence.json",
        "paper_evidence_markdown_sha256": run_root / "paper_evidence.md",
        "paper_numeric_audit_sha256": run_root / "paper_numeric_audit.json",
        "selection_freeze_sha256": run_root / "selection_freeze.json",
    }
    for field, path in bindings.items():
        if not path.is_file():
            raise RuntimeError(f"Final-paper manifest artifact is missing: {path}")
        if payload.get(field) != _sha256(path):
            raise RuntimeError(f"Final-paper manifest hash mismatch: {field}")
    holdout = run_root / "holdout_summary.json"
    expected_holdout = payload.get("holdout_summary_sha256")
    if expected_holdout is None:
        if holdout.exists():
            raise RuntimeError("Final-paper manifest omits an existing holdout summary")
    elif not holdout.is_file() or expected_holdout != _sha256(holdout):
        raise RuntimeError("Final-paper manifest holdout hash mismatch")
    numeric = _read_json(run_root / "paper_numeric_audit.json")
    claims = _read_json(run_root / "claim_verification.json")
    if numeric.get("passed") is not True or claims.get("passed") is not True:
        raise RuntimeError("Final-paper manifest binds a failed audit")
    return payload


def finalize(
    *,
    run_root: Path,
    model: str,
    engine: str,
    stable_manifest: Path | None,
    force: bool,
) -> dict[str, Any]:
    run_root = run_root.resolve()
    existing = run_root / "final_paper_manifest.json"
    if existing.is_file() and not force:
        payload = validate_existing_manifest(run_root)
        print("Existing final paper matches its full artifact contract; no provider call was made.")
        return payload

    _validate_final_prerequisites(run_root)
    verified_tex, claims_path = generate_verified_results(run_root)
    claims = _read_json(claims_path)
    verification = verify_claims(run_root, claims)
    if not verification["passed"]:
        raise RuntimeError("Verified claim generation failed provenance checks")
    verification_path = run_root / "claim_verification.json"
    _atomic_json(verification_path, verification)

    idea = _load_selected_idea(run_root)
    evidence_json, evidence_md = _make_evidence(run_root, idea)
    evidence_hash = _sha256(evidence_md)
    tex_path = run_root / "latex" / "template.tex"
    if not tex_path.is_file():
        raise FileNotFoundError(tex_path)

    client, client_model = create_client(model)
    io = InputOutput(
        yes=True,
        chat_history_file=str(run_root / "final_paper_aider.txt"),
    )
    coder = Coder.create(
        main_model=Model(get_aider_model_name(model)),
        fnames=[str(tex_path)],
        io=io,
        stream=False,
        use_git=False,
        edit_format="diff",
    )
    perform_writeup(
        idea,
        str(run_root),
        coder,
        client,
        client_model,
        num_cite_rounds=8,
        engine=engine,
    )
    assert_no_placeholders(str(run_root))
    if _sha256(evidence_md) != evidence_hash:
        raise RuntimeError("paper_evidence.md changed during write-up")

    generated = run_root / f"{idea['Name']}.pdf"
    if not generated.is_file():
        raise FileNotFoundError(generated)
    final_paper = run_root / "final_policy_paper.pdf"
    shutil.copy2(generated, final_paper)

    audit_path = run_root / "paper_numeric_audit.json"
    numeric_audit = audit_paper_numbers(tex_path)
    _atomic_json(audit_path, numeric_audit)
    if not numeric_audit["passed"]:
        coder.run(
            "Remove or rewrite every unverified decimal or percentage outcome value in "
            "latex/template.tex. Refer to the machine-generated verified tables instead. "
            "Findings: "
            + json.dumps(numeric_audit["findings"], ensure_ascii=False)
        )
        generate_latex(coder, str(run_root), str(generated))
        assert_no_placeholders(str(run_root))
        numeric_audit = audit_paper_numbers(tex_path)
        _atomic_json(audit_path, numeric_audit)
        if not numeric_audit["passed"]:
            raise RuntimeError(
                "Final manuscript still contains unverified decimal/percentage prose"
            )
        shutil.copy2(generated, final_paper)

    manifest = {
        "schema_version": "1.0",
        "status": "complete",
        "phase": "post_selection_post_holdout_final_paper",
        "model": model,
        "citation_engine": engine,
        "generated_at_utc": datetime.now(timezone.utc).replace(
            microsecond=0
        ).isoformat(),
        "run_root": str(run_root),
        "final_paper_path": str(final_paper.resolve()),
        "final_paper_sha256": _sha256(final_paper),
        "latex_sha256": _sha256(tex_path),
        "verified_results_sha256": _sha256(verified_tex),
        "verified_claims_sha256": _sha256(claims_path),
        "claim_verification_path": str(verification_path.resolve()),
        "claim_verification_sha256": _sha256(verification_path),
        "paper_evidence_json_sha256": _sha256(evidence_json),
        "paper_evidence_markdown_sha256": _sha256(evidence_md),
        "paper_numeric_audit_sha256": _sha256(audit_path),
        "selection_freeze_sha256": _sha256(run_root / "selection_freeze.json"),
        "holdout_summary_sha256": (
            _sha256(run_root / "holdout_summary.json")
            if (run_root / "holdout_summary.json").is_file()
            else None
        ),
        "claim_boundary": (
            "Final manuscript reports synthetic development and frozen holdout evidence only; no real-world causal effect is claimed."
        ),
    }
    _atomic_json(existing, manifest)
    _update_result_manifests(
        run_root=run_root,
        stable_manifest=stable_manifest,
        final_manifest=manifest,
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-root", type=Path, required=True)
    parser.add_argument("--model", default="gemini-2.5-pro")
    parser.add_argument(
        "--engine", default="semanticscholar", choices=["semanticscholar", "openalex"]
    )
    parser.add_argument("--result-manifest", type=Path, default=None)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--check-existing-only", action="store_true")
    args = parser.parse_args()
    if args.check_existing_only:
        try:
            existing = validate_existing_manifest(args.run_root.resolve())
        except Exception as exc:
            print(f"Existing final paper is stale: {exc}")
            raise SystemExit(2)
        if existing is None:
            print("No final paper exists yet.")
            raise SystemExit(3)
        print(json.dumps(existing, ensure_ascii=False, indent=2))
        return
    result = finalize(
        run_root=args.run_root,
        model=args.model,
        engine=args.engine,
        stable_manifest=args.result_manifest,
        force=args.force,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
